<?php
/**
 * Created by PhpStorm.
 * User: my1-asus
 * Date: 12/22/15
 * Time: 9:05 AM
 */
$form = $this->form;
$title = 'Register';
$this->headTitle($title);
?>
<html>
<head>
<h1><?php echo $this->escapeHtml($title); ?></h1>
</head>
<body>
<?php
// we prepare de form
$form->prepare();

echo $this->form()->openTag($form);
?>
<head>
     <span>
        <a href="<?php echo $this->url('myProfiPhoto', array('action'=>'index'));?>"  class="btn-link">Home</a>
        <br>
    </span>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<div class="form_element">
    <div class="control_group">
        <div class="controls"><?php echo $this->formInput($form->get('id')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('firstName')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('firstName')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('lastName')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('lastName')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('birthDate')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('birthDate')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('username')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('username')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('email')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('email')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('password')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('password')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('confirmPassword')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <div class="controls"><?php echo $this->formInput($form->get('confirmPassword')); ?></div>
    </div>
    <div class="control_group">
        <?php echo $this->formLabel($form->get('gender')); ?>
        <div class="controls"><?php echo $this->formRadio($form->get('gender')); ?></div>
    </div>
    <div class="control_group">
        <div class="g-recaptcha" data-sitekey="6Lf9pxMTAAAAAMWB_ve9qCZIPVkUTZJf1xQILYVK"></div>
    </div>
    <div class="control_group">
        <div class="controls"><?php echo $this->formInput($form->get('submit')); ?></div>
    </div>
    <span>
        <a href="<?php echo $this->url('myProfiPhoto', array('action'=>'register'));?>"  class="btn-link">Reset Form</a>
        <br>
    </span>

</div>

<?php
echo $this->form()->closeTag($form);
?>
</body>
</html>
